### ISSUE TITLE
Compiled veg survey data tidying

### ISSUE THREAD

**Issue by cjlortie** [cjlortie/RMR.harding#3]
- [x] clean up treatment codes
- [x] replace all short-cut codes with words
- [x] add a microsite column for the house-field bit
- [ ] add in 2006 and 2010 so that we have a real compiled dataset and we can just use R to filter out what years we need for each analysis
- [x] anything else you can think of to this dataframe.

**Comment by ekswan** [comment]
Done-clean up treatment codes
 Done-replace all short-cut codes with words
 Doneadd a microsite column for the house-field bit
 Added 2010, but not 2006. Will take finageling, lots missing and columns in different order ----add in 2006 and 2010 so that we have a real compiled dataset and we can just use R to filter out what years we need for each analysis
 Fixed a few other columns, joined data from 2010 missing columns-----anything else you can think of to this dataframe

**Comment by cjlortie** [comment]
good for me.
we can convert 2006 to similar format in R.
